const colorDescriptions = [
    { letra: 'a', cor: 'azul', description: 'BLUE | HSB 100 - W 11', img: "blue.png" },
    { letra: 'c', cor: 'amarelo', description: 'YELLOW | HSB 100 - G 12', img: "yellow.png" },
    { letra: 'e', cor: 'vermelho', description: 'RED | HSB 100 - AJ 11', img: "red.png" },
    { letra: 'b', cor: 'verde', description: 'GREEN | HSB 100 - O 10', img: "green.png" },
    { letra: 'd', cor: 'laranja', description: 'ORANGE | HSB 100 - C 11', img: "orange.png" },
    { letra: 'f', cor: 'roxo', description: 'PURPLE | HSB 100 - AB 11', img: "purple.png" },
    { letra: 'g', cor: 'castanho', description: 'BROWN | HSB 100 - E 15', img: "brown.png" },
    { letra: 'v', cor: 'branco', description: 'WHITE | HSB 10 - A 2', img: "white.png" },
    { letra: 'y', cor: 'preto', description: 'BLACK | HSB 33 - A 21', img: "black.png" },
    { letra: 'h', cor: 'azul claro', description: 'LIGHT BLUE | HSB 100 - S 11', img: "light_blue.png" },
    { letra: 'j', cor: 'amarelo claro', description: 'LIGHT YELLOW | HSB 66 - G 9', img: "light_yellow.png" },
    { letra: 'l', cor: 'vermelho claro', description: 'LIGHT RED | HSB 33 - AG 9', img: "light_red.png" },
    { letra: 'i', cor: 'verde claro', description: 'LIGHT GREEN | HSB 100 - J 10', img: "light_green.png" },
    { letra: 'k', cor: 'laranja claro', description: 'LIGHT ORANGE | HSB 100 - E 8', img: "light_orange.png" },
    { letra: 'm', cor: 'roxo claro', description: 'LIGHT PURPLE | HSB 100 - AD 7', img: "light_purple.png" },
    { letra: 'n', cor: 'castanho claro', description: 'LIGHT BROWN | HSB 66 - E 9', img: "light_brown.png" },
    { letra: 'w', cor: 'cinza claro', description: 'LIGHT grey | HSB 10 - D 14', img: "light_grey.png" },
    { letra: 'x', cor: 'rosa claro', description: 'LIGHT RED | HSB 33 - AG 9', img: "light_red.png" },
    { letra: 'o', cor: 'azul escuro', description: 'DARK BLUE | HSB 100 - Y 17', img: "dark_blue.png" },
    { letra: 'q', cor: 'amarelo escuro', description: 'DARK YELLOW | HSB 100 - F 11', img: "dark_yellow.png" },
    { letra: 's', cor: 'vermelho escuro', description: 'DARK RED | HSB 100 - A 17', img: "dark_red.png" },
    { letra: 'p', cor: 'verde escuro', description: 'DARK GREEN | HSB 100 - L 17', img: "dark_green.png" },
    { letra: 'r', cor: 'laranja escuro', description: 'DARK ORANGE | HSB 100 - C 12', img: "dark_orange.png" },
    { letra: 't', cor: 'roxo escuro', description: 'DARK PURPLE | HSB 100 - AB 17', img: "dark_purple.png" },
    { letra: 'u', cor: 'castanho escuro', description: 'DARK BROWN | HSB 100 - D 19', img: "dark_brown.png" },
    { letra: 'z', cor: 'cinza escuro', description: 'DARK grey | LUM-80 - G 2', img: "dark_grey.png" }
];
